export type SupportedLenderVisualTier = 'major' | 'tier2' | 'regional' | 'specialist' | 'channel'

export type SupportedLender = {
  name: string
  slug: string
  group: string
  shortGroup: string
  visualTier: SupportedLenderVisualTier
  heroOrder: number
  faqOrder: number
}

const MAJOR_BANK_GROUP = 'Major banks'
const TIER_2_GROUP = 'Tier-2 banks and major-bank subsidiaries'
const REGIONAL_GROUP = 'Regional and customer-owned banks'
const SPECIALIST_GROUP = 'Specialist lenders'
const CHANNEL_GROUP = 'Wholesale, aggregator, and government-backed channels'

// Keep this as the canonical coverage ledger for both the hero field and FAQ answer.
// heroOrder preserves the market-weighted hero sequence; faqOrder preserves the
// existing FAQ sequence so visible copy and schema output stay aligned.
export const SUPPORTED_LENDERS = [
  {
    name: 'Commonwealth Bank',
    slug: 'commonwealth-bank',
    group: MAJOR_BANK_GROUP,
    shortGroup: 'Major bank',
    visualTier: 'major',
    heroOrder: 1,
    faqOrder: 15,
  },
  {
    name: 'Westpac',
    slug: 'westpac',
    group: MAJOR_BANK_GROUP,
    shortGroup: 'Major bank',
    visualTier: 'major',
    heroOrder: 2,
    faqOrder: 36,
  },
  {
    name: 'NAB',
    slug: 'nab',
    group: MAJOR_BANK_GROUP,
    shortGroup: 'Major bank',
    visualTier: 'major',
    heroOrder: 3,
    faqOrder: 27,
  },
  {
    name: 'ANZ',
    slug: 'anz',
    group: MAJOR_BANK_GROUP,
    shortGroup: 'Major bank',
    visualTier: 'major',
    heroOrder: 4,
    faqOrder: 5,
  },
  {
    name: 'Macquarie',
    slug: 'macquarie',
    group: MAJOR_BANK_GROUP,
    shortGroup: 'Major bank',
    visualTier: 'major',
    heroOrder: 5,
    faqOrder: 25,
  },
  {
    name: 'Bankwest',
    slug: 'bankwest',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 6,
    faqOrder: 11,
  },
  {
    name: 'Bank of Queensland',
    slug: 'bank-of-queensland',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 7,
    faqOrder: 9,
  },
  {
    name: 'Bendigo Bank',
    slug: 'bendigo-bank',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 8,
    faqOrder: 12,
  },
  {
    name: 'Suncorp',
    slug: 'suncorp',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 9,
    faqOrder: 33,
  },
  {
    name: 'ING',
    slug: 'ing',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 10,
    faqOrder: 19,
  },
  {
    name: 'AMP Bank',
    slug: 'amp-bank',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 11,
    faqOrder: 4,
  },
  {
    name: 'St George',
    slug: 'st-george',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 12,
    faqOrder: 32,
  },
  {
    name: 'UBank',
    slug: 'ubank',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 13,
    faqOrder: 35,
  },
  {
    name: 'ME Bank',
    slug: 'me-bank',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 14,
    faqOrder: 24,
  },
  {
    name: 'Adelaide Bank',
    slug: 'adelaide-bank',
    group: TIER_2_GROUP,
    shortGroup: 'Tier-2 bank',
    visualTier: 'tier2',
    heroOrder: 15,
    faqOrder: 1,
  },
  {
    name: 'Bank Australia',
    slug: 'bank-australia',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 16,
    faqOrder: 8,
  },
  {
    name: 'Heritage Bank',
    slug: 'heritage-bank',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 17,
    faqOrder: 18,
  },
  {
    name: 'Great Southern Bank',
    slug: 'great-southern-bank',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 18,
    faqOrder: 17,
  },
  {
    name: 'Beyond Bank',
    slug: 'beyond-bank',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 19,
    faqOrder: 13,
  },
  {
    name: 'Auswide Bank',
    slug: 'auswide-bank',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 20,
    faqOrder: 7,
  },
  {
    name: 'Bank of Sydney',
    slug: 'bank-of-sydney',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 21,
    faqOrder: 10,
  },
  {
    name: 'MyState',
    slug: 'mystate',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 22,
    faqOrder: 26,
  },
  {
    name: 'Police & Nurses',
    slug: 'police-and-nurses',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 23,
    faqOrder: 29,
  },
  {
    name: 'Teachers Mutual Bank',
    slug: 'teachers-mutual-bank',
    group: REGIONAL_GROUP,
    shortGroup: 'Regional bank',
    visualTier: 'regional',
    heroOrder: 24,
    faqOrder: 34,
  },
  {
    name: 'Liberty Financial',
    slug: 'liberty-financial',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 25,
    faqOrder: 22,
  },
  {
    name: 'Pepper Money',
    slug: 'pepper-money',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 26,
    faqOrder: 28,
  },
  {
    name: 'Resimac',
    slug: 'resimac',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 27,
    faqOrder: 31,
  },
  {
    name: 'Firstmac',
    slug: 'firstmac',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 28,
    faqOrder: 16,
  },
  {
    name: 'La Trobe Financial',
    slug: 'la-trobe-financial',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 29,
    faqOrder: 21,
  },
  {
    name: 'Bluestone',
    slug: 'bluestone',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 30,
    faqOrder: 14,
  },
  {
    name: 'Athena',
    slug: 'athena',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 31,
    faqOrder: 6,
  },
  {
    name: 'MA Money',
    slug: 'ma-money',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 32,
    faqOrder: 23,
  },
  {
    name: 'RedZed',
    slug: 'redzed',
    group: SPECIALIST_GROUP,
    shortGroup: 'Specialist lender',
    visualTier: 'specialist',
    heroOrder: 33,
    faqOrder: 30,
  },
  {
    name: 'Advantedge',
    slug: 'advantedge',
    group: CHANNEL_GROUP,
    shortGroup: 'Policy channel',
    visualTier: 'channel',
    heroOrder: 34,
    faqOrder: 2,
  },
  {
    name: 'AFG',
    slug: 'afg',
    group: CHANNEL_GROUP,
    shortGroup: 'Policy channel',
    visualTier: 'channel',
    heroOrder: 35,
    faqOrder: 3,
  },
  {
    name: 'Keystart',
    slug: 'keystart',
    group: CHANNEL_GROUP,
    shortGroup: 'Policy channel',
    visualTier: 'channel',
    heroOrder: 36,
    faqOrder: 20,
  },
] satisfies SupportedLender[]

export const supportedLendersByMarketCap = [...SUPPORTED_LENDERS].sort(
  (first, second) => first.heroOrder - second.heroOrder,
)

export const bulmaCoveredLenders = [...SUPPORTED_LENDERS]
  .sort((first, second) => first.faqOrder - second.faqOrder)
  .map((lender) => lender.name)

export const bulmaCoveredLendersAnswer = `Bulma currently has policy coverage for ${bulmaCoveredLenders.length} lenders: ${bulmaCoveredLenders.join(
  ', ',
)}. We update this list as new lender policies are added and refreshed.`
